import {
  StyleSheet
} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  surface: {
    elevation: 12,
    borderRadius: 20,
    shadowColor: '#0f172a',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    backgroundColor: '#ffffff',
    padding: 28,
    width: '92%',
    maxWidth: 440,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  modalContent: {
    margin: 8,
    backgroundColor: 'transparent',
    flex: 1,
    justifyContent: 'center',
  },
  modalCard: {
    borderRadius: 20,
    maxHeight: '92%',
    minHeight: '75%',
    elevation: 16,
    shadowColor: '#0f172a',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
  },
  searchBar: {
    marginBottom: 20,
    elevation: 2,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    fontSize: 16,
    height: 56,
    minHeight: 56,
  },
  contactsList: {
    maxHeight: 420,
    minHeight: 320,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    flex: 1,
  },
  contactItem: {
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginVertical: 3,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#f1f5f9',
    minHeight: 72,
    elevation: 1,
    shadowColor: '#64748b',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  contactSection: {
    marginBottom: 24,
  },
  selectedContactCard: {
    marginTop: 12,
    backgroundColor: '#f0f9ff',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#0ea5e9',
    elevation: 3,
    shadowColor: '#0ea5e9',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  selectContactButton: {
    marginVertical: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#0ea5e9',
    height: 52,
    backgroundColor: 'transparent',
  },
  divider: {
    marginVertical: 24,
    height: 1,
    backgroundColor: '#e2e8f0',
  },
  intervalSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    marginBottom: 16,
    fontWeight: '700',
    color: '#0f172a',
    letterSpacing: -0.5,
  },
  intervalButtons: {
    marginBottom: 16,
    backgroundColor: '#f8fafc',
    borderRadius: 14,
    padding: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  intervalButton: {
    flex: 1,
    borderRadius: 10,
    marginHorizontal: 2,
  },
  customIntervalInput: {
    marginTop: 16,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    height: 56,
    minHeight: 56,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 28,
    gap: 16,
  },
  button: {
    marginTop: 28,
    borderRadius: 14,
    elevation: 6,
    shadowColor: '#0f172a',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    height: 56,
    backgroundColor: '#0ea5e9',
  },
  startButton: {
    backgroundColor: '#059669',
    borderRadius: 14,
    elevation: 6,
    shadowColor: '#059669',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  stopButton: {
    backgroundColor: '#dc2626',
    borderRadius: 14,
    elevation: 6,
    shadowColor: '#dc2626',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  errorChip: {
    backgroundColor: '#fef2f2',
    marginVertical: 20,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#fecaca',
    elevation: 3,
    shadowColor: '#dc2626',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  errorText: {
    color: '#dc2626',
    fontWeight: '600',
    fontSize: 15,
  },
  statusCard: {
    marginTop: 28,
    backgroundColor: '#f0fdf4',
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#86efac',
    elevation: 4,
    shadowColor: '#059669',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  backgroundImage: {
    flex: 1,
  },
  backgroundImageStyle: {
    opacity: 0.05,
  },
  titleContainer: {
    alignItems: 'center',
    marginBottom: 36,
  },
  input: {
    marginBottom: 24,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    elevation: 2,
    shadowColor: '#64748b',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    height: 56,
    minHeight: 56,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingVertical: 12,
    paddingHorizontal: 20,
    elevation: 12,
    shadowColor: '#0f172a',
    shadowOffset: {
      width: 0,
      height: -4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 16,
    marginHorizontal: 6,
    backgroundColor: 'transparent',
  },
  activeTab: {
    backgroundColor: '#f0f9ff',
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
    marginTop: -6,
    letterSpacing: 0.3,
  },
  activeTabText: {
    color: '#0ea5e9',
    fontWeight: '700',
  }
});