import {
  StyleSheet
} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  surface: {
    elevation: 20,
    borderRadius: 24,
    shadowColor: '#1a1a2e',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 32,
    width: '90%',
    maxWidth: 420,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  modalContent: {
    margin: 20,
    backgroundColor: 'transparent',
  },
  modalCard: {
    borderRadius: 24,
    maxHeight: '80%',
    elevation: 15,
    shadowColor: '#1a1a2e',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  searchBar: {
    marginBottom: 20,
    elevation: 0,
    backgroundColor: 'rgba(248, 250, 252, 0.9)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.5)',
  },
  contactsList: {
    maxHeight: '70%',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
  },
  contactItem: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginVertical: 4,
    backgroundColor: 'rgba(248, 250, 252, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.3)',
  },
  contactSection: {
    marginBottom: 20,
  },
  selectedContactCard: {
    marginTop: 8,
    backgroundColor: '#f8f9ff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0e7ff',
    elevation: 2,
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  selectContactButton: {
    marginVertical: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#e0e7ff',
    height: 50,
  },
  divider: {
    marginVertical: 20,
    height: 1,
    backgroundColor: '#e0e7ff',
  },
  intervalSection: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    marginBottom: 12,
    fontWeight: '600',
    color: '#1f2937',
  },
  intervalButtons: {
    marginBottom: 12,
    backgroundColor: '#f8f9ff',
    borderRadius: 12,
    padding: 4,
  },
  intervalButton: {
    flex: 1,
    borderRadius: 8,
  },
  customIntervalInput: {
    marginTop: 12,
    backgroundColor: '#f8f9ff',
    borderRadius: 12,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    gap: 12,
  },
  button: {
    marginTop: 24,
    borderRadius: 16,
    elevation: 8,
    shadowColor: '#4f46e5',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    height: 56,
    backgroundColor: '#4f46e5',
  },
  startButton: {
    backgroundColor: '#059669',
    borderRadius: 16,
    elevation: 6,
    shadowColor: '#059669',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  stopButton: {
    backgroundColor: '#dc2626',
    borderRadius: 16,
    elevation: 6,
    shadowColor: '#dc2626',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  errorChip: {
    backgroundColor: 'rgba(254, 242, 242, 0.9)',
    marginVertical: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(252, 165, 165, 0.4)',
    elevation: 4,
    shadowColor: '#dc2626',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  errorText: {
    color: '#dc2626',
    fontWeight: '600',
    fontSize: 14,
  },
  statusCard: {
    marginTop: 24,
    backgroundColor: 'rgba(236, 253, 245, 0.9)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(167, 243, 208, 0.4)',
    elevation: 6,
    shadowColor: '#059669',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  backgroundImage: {
    flex: 1,
  },
  backgroundImageStyle: {
    opacity: 0.3,
  },
  titleContainer: {
    alignItems: 'center',
    marginBottom: 32,
  },
  input: {
    marginBottom: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 16,
    elevation: 4,
    shadowColor: '#1e293b',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  }
});